ara-software/AraRoot

- AraEvent/AraEventConditioner.cxx
- AraEvent/AraEventConditioner.h
- AraEvent/AraQualCuts.cxx
- AraEvent/CMakeLists.txt
- AraEvent/LinkDef.h
- AraEvent/UsefulAtriStationEvent.cxx
- AraEvent/UsefulAtriStationEvent.h
This branch introduces the AraEventConditioner class, which enables us to condition waveforms further after we calibrate them.
It moves the previous trimGraph function from the UsefulAtriStationEvent class to the AraEventConditioner class, which is a more appropriate place for it.
> feature__cond-class

- AraEvent/AraGeomTool.cxx
- AraEvent/AraStationInfo.cxx
This converts all the `sqlite3_open()` statements in the geometry tools to "read only", to attempt to make file access safer on NFS filesystems, which do not like SQLite (https://www.sqlite.org/faq.html#q5). This attempts to address #10.
It also includes clean up of tabs in that class, along with some improved debug statements.
> bug__sqlite-read

- AraEvent/UsefulAtriStationEvent.cxx
make it so that event conditioning doesn't happen if the user is asking for a primitive calibration type, e.g. kNoCalib or kJustPed
> don't condition primitive calibration types

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
- AraCorrelator/RayTraceCorrelator_support/docs/README.md
- AraCorrelator/makeRTCorrelationMaps.cxx
This update to the RayTraceCorrelator removes the icemodel and unixtime dependencies, which essentially makes the ray trace correlator work on any data, not just ARA data. It also means the tables are not tied to the AraSim iceModel paradigm.
> Update to the RayTraceCorrelator

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
- AraCorrelator/RayTraceCorrelator_detail.h
- AraCorrelator/RayTraceCorrelator_support/docs/README.md
- AraCorrelator/makeRTCorrelationMaps.cxx
The major change here is a modification to the Ray Trace Correlator API. Namely that it is now the users responsibility to calculate the correlation function themselves.
This is a big win in the case where you want to make multiple maps. It turns out making the correlation graphs is about 70% of the run time of the correlator. So if you need to make multiple maps (e.g. D'n'R, radii scans, etc.) it is a major advantage to have the correlation functions cached.
> Adjust the RTC API

- AraEvent/AraEventCalibrator.cxx
**1. place CommonMode() step before TimingCalibrationAndBadSampleReomval() step**
This function is subtracting DDA ch5 value from DDA ch1 ~ 4.
But the purpose of this function is unknown. And the return of the `hasCommonMode ()` is always `kFalse`.
Since it will only work when the number of samples between DDA ch 1~4 and ch 5 is the same,
It is placed before `TrimFirstBlock()` and `TimingCalibrationAndBadSampleReomval()`
**2. High ADC treatment for A5**
For A5, since there is no high ADC calibration data, use ADC count for voltage calibration result in case A5 encounters high ADC count (out of -500 ~ 500 ADC range)
Not sure of contents of the `araAtriStation5highAdcToVoltsConv.txt` table.
> Updating CommonMode() step and High ADC treatment for A5

- AraEvent/AraEventCalibrator.cxx
- AraEvent/AraEventCalibrator.h
**1. kLatestCalibWithOutZeroMean**
Performs every calibration except the ADC and Voltage zero meaning. 
Since the zero meaning function is an additional correction for calibration, I added the mode to turn off the correction.
By this mode, the user can check how much offset that WF can have from 0 after pedestal subtraction.
**2. kOnlyGoodADC** 
Apply only time calibration to WF
It will print out the raw ADC WF without bad samples and pedestal subtraction.
If the user chooses this mode to calibrate the WF, It turn on only `TrimFirstBlock()`, `TimingCalibrationAndBadSampleReomval()` and `ApplyCableDelay()`.
So, users can check the only good raw ADC samples.
**3. kOnlyGoodPed**
Since there is no method to check what is the pedestal values for the corresponding WF through AraRoot, I …
> Adding new CalType mode

- utilities/repeder/repeder.cc
1. `int sum` in `get_median_slice()` need to be `double sum` to get the correct half of the cumulative frequency. for example, If the `sum` is 1 (basically only one count in the middle of the histogram) and it is still an integer, `sum/2` would be 0, and the median calculation will results always the beginning of the histogram no matter where one count is...
2. Initial `iblk` needs to be 4 to remove 1st block from all 4 DDA boards since the IRS number format is like below
[1st blk in DDA1, 1st blk in DDA2, 1st blk in DDA3, 1st blk in DDA4, 2nd blk in DDA1, 2ndblk in DDA2, 2ndblk in DDA3, 2ndblk in DDA4,  ...]
If Initial `iblk` is 1, It will remove only 1st blk in DDA1
> 2nd repeder updates

- AraEvent/AraEventCalibrator.cxx
- AraEvent/AraEventCalibrator.h
To identify offset from 0 after pedestal subtraction, I added two more calibration type
1) **kJustPedWithOut1stBlock**
It will perform only `PedestalSubtraction()` and `TrimFirstBlock()`
2) **kJustPedWithOut1stBlockAndBadSamples**
It will perform only `PedestalSubtraction()`, `TrimFirstBlock()`,` TimingCalibrationAndBadSampleReomval()` and `ApplyCableDelay()`
The number of samples and time width betweens samples will be the same as fully calibrated WF (kLatestCalib). So, users can easily to compare the result with calibrated WF.
> Adding new AraCalType v3

- AraEvent/AraQualCuts.cxx
- AraEvent/AraQualCuts.h
#40 Update AraQualCuts short waveform criteria
A function named `hasTooFewSamples()` was added in both files **AraQualCuts.cxx** and **AraQualCuts.h**, this function detects waveforms whose number of samples is less than 500 (too few samples).
> Martin01021207 patch 1

- AraEvent/AraQualCuts.cxx
Software triggers were not passing quality cut on number of samples. Added an exception for software triggers to bypass this.
> Added exception so that softTrigs pass quality cuts.

- AraEvent/AraEventCalibrator.cxx
- AraEvent/AraEventCalibrator.h
This reverts commit 9b4dc4a7b07e2beb0ccca0e228f424cd50ae72e2.
> Revert "Option for full calibration without first block trimming  (#53)"

- AraEvent/AraEventCalibrator.cxx
- AraEvent/AraEventCalibrator.h
Added a check to make sure the `stationId` of data matches that of the pedestal file requested by the user, if they have requested a specific pedestal file. This mostly ensures that pedestal files for the A1 ATRI station aren't accidentally assigned to the A1 ICRR station internally, which can cause the wrong (default) pedestal file to be loaded by mistake without the user realizing.
One caveat is that this solution depends on the station `calibIndex` which is _not_ unique. Namely, `ARA_TESTBED` and `ARA_STATION1B` share `calibIndex=0`, while `ARA_STATION1` and `ARA_STATION2` share `calibIndex=1`. This seems unlikely to cause an issue but has been noted in a comment.
> Error check to avoid A1 pedestal confusion between ATRI and ICRR stations

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
- AraCorrelator/RayTraceCorrelator_support/make_timing_tables/makeRTArrivalTimeTables.cpp
Added calculation and output of the launch angles of the RF signal from a source vertex.  The Ray Tracer natively calculated the receiving and launch angles with respect to the position vector of the receiver antenna (referred to as **_target_** in the code).  A diagram of the vector geometry can be seen in the image below:
where **_target_** is the position vector of the receiver antenna relative to the center of the Earth, **_source_** is the position vector of the source vertex relative to the center of the Earth.  As implied by the names, _**launchVector**_ and _**receiveVector**_ are the trajectories of the RF signal at the source and receiver, respectively.  Within the Ray Tracer, there are values for _**launchAngle**_ and **_receiptAngle_**, which are measured with respect the the …
> Added support for launch angles of RF signal from source.

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
- AraCorrelator/RayTraceCorrelator_detail.h
This PR changes the correlation routine called by default in the RayTraceCorrelator. The previous one, which tried to account for trace lengths, is just a little to slow for standard multipurpose use. This one is a couple orders of magnitude faster. It takes about 10 milliseconds to make the vpol and hpol cross-corr functions, while the previous algorithm took about 5 seconds (both when called from pyroot).
To do this, I also had to introduce a function to normalize the waveforms by their RMS before they enter the correlator.
> Update the correlation routine in the RayTraceCorrelator

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
- AraCorrelator/RayTraceCorrelator_detail.h
- AraCorrelator/makeRTCorrelationMaps.cxx
Major update to the RayTraceCorrelator.
Namely, I have rewritten the getCorrFunctions method to use unique pointers for internal management, and to return a vector of TGraphs, instead of TGraph*. So std::vector<TGraph> instead of std::vector<TGraph*>.
I also modified the GetInterferometricMap routine to take as an input the vector<TGraph>, and it now returns a TH2D, not TH2D*. This is done to make these objects much more memory safe, especially when called from pyroot.
> make update to the RTC

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
- AraCorrelator/RayTraceCorrelator_support/docs/README.md
- AraCorrelator/makeRTCorrelationMaps.cxx
This is a pretty substantial optimization effort undertake with @marcomuzio.
We added caching of the arrival delays for pairs, since this is stable across events.
We also worked pretty hard to make the map  making routine leaner and meaner.
This involves make it slightly less readable, and in some ways, less safe.
E.g. we pulled out some sanity checks (if statements) to make things faster.
So be careful!
Overall we found about a factor of 5-6 speed improvement in the time needed to call the map routine. So we think that's worth it.
> Speed up the ray trace correlator

- AraCorrelator/RayTraceCorrelator.cxx
- AraCorrelator/RayTraceCorrelator.h
A segfault was being thrown when programs using the RTC were ended. This seems to have been due to ROOT owning the `TH2D` created via `new`, causing the same object to be destructed twice: once by ROOT and once by the `std::shared_ptr`. Using `std::make_shared` seems to avoid this by ensuring only the `std::shared_ptr` owns the object. (I also updated the get function for the template map to use a `std::weak_ptr` to avoid any chance of circular references.)
This was a little subtle to understand, so admittedly I appealed to chatgpt. Here's its explanation which may be more clear:
You are a c++ expert, in particular with the ROOT library. Why does this code cause a segfault on destruction:
int numPhiBins_ = 360;
int numThetaBins_ = 180;
std::shared_ptr<TH2D> dummyMap;
dummyMap = …
> Fixed segfault on RTC destructor call

- AraEvent/AraEventCalibrator.cxx
- AraEvent/AraEventCalibrator.h
Added functions to correct block offsets. This is based on an algorithm used in RNO-G, but here we solve for the offsets using a matrix equation rather than an optimizer. 
The correction is done channel-by-channel and does add some overhead to calibration due to the FFT needed per-channel and solving the matrix equation. To mitigate for this, the correction is currently only applied to the 4 used channels on each DDA. The exact amount of overhead added varies slightly station-to-station, (I think) because it scales with the number of samples in the calibrated trace.
To give an idea, a quick benchmark of the total time to perform the full calibration (really to execute `realAtriEvent = new UsefulAtriStationEvent(rawAtriEvent, AraCalType::kLatestCalib);`) is roughly:
- 0.011 s/event …
> Block offset correction

- AraEvent/AraEventCalibrator.cxx
- AraEvent/AraEventCalibrator.h
Implemented changes based on feedback from [PR#85](https://github.com/ara-software/AraRoot/pull/85). I added a calibration option to implement `kLatestCalib` but without the block offset correction, `kLatestCalib_NoBlockCorrection`.
In particular, I investigated using Eigen3 to solve the linear system of equations but found that it was slower than the ROOT implementation. In any case, this part of the function is not a bottleneck and either implementation does not significantly change the function's run time. The main bottlenecks in the function are the first FFT (for the first event calibrated) and then filling the matrix of constants (for events after the first calibration). 
Here is an updated benchmarking of the correction compared to the time for the full calibration. Note that due …
> Final block offset correction updates

- AraEvent/AraQualCuts.cxx
- AraEvent/AraQualCuts.h
This updates the livetime configuration log read in to read in the trigger and readout window columns added in [PR#86](https://github.com/ara-software/AraRoot/pull/86). Also adds corresponding get functions. 
NOTE: This update _will_ break AraProc for stations whose logs are not yet updated.
> Update livetime config log read in

- AraEvent/AraEventCalibrator.cxx
- INSTALL.sh
- README.md
This fixes a segfault that occurs when trying to access elements of a time and voltage vector with no points. An if statement was added to ensure there is data to be corrected before attempting and if there isn't the function moves to the next channel.
Also added an option in `INSTALL.sh` to make a debug build to aid in debugging.
> Fixed bug in block offset correction

- AraEvent/AraEventCalibrator.cxx
This PR fixes a memory leak that was introduced with the block offset correction part of calibration. I don't completely understand it, but it originated from the `blockList` vector being defined using `new` and then filled with `push_back` (despite a call to `delete` to clean up this vector). Changing the initialization to _not_ use `new` and passing the vector by reference fixes the leak.
Two other vectors are also defined in this way, `sampleList` and `capArrayList` (which I patterned `blockList` on). These follow a very similar set of operations in the calibration, so it's a bit of a mystery to me why they do not seem to cause a leak. However, to be safe I've converted these to also use standard `vector` initialization and to be passed by reference to functions.
> Fixed memory leak introduced in block offset correction

- AraEvent/AraEventCalibrator.cxx
- test/fileAndEventCal.cxx
Changed behavior to crash if the passed pedestal does not load properly. If no pedestal is passed by the user, the code will crash and give a message suggesting where one might find the default pedestals.
My only concern is whether this might break AWARE.
> Removed fallback to default pedestals.

- AraEvent/RawAtriStationEvent.h
Added a function to check for a PA trigger, inferred from the lack of RF and software trigger tags. This is really only for A5 but should still work for other stations, just always returning false.
> Added PA trigger type
